apiVersion: v1
kind: ConfigMap
metadata:
  name: tumbo-config
  namespace: tumbo
data:
  log_level: INFO
  DB_HOST: db
  DB_NAME: planet
  DB_PORT: '5432'
  DB_USER: planet
  JOBSTOREDB_NAME: jobstore
  JOBSTOREDB_USER: jobstore
  JOBSTOREDB_PORT: '5432'
  JOBSTOREDB_HOST: jobstoredb
  TUMBO_WORKER_IMPLEMENTATION: core.executors.worker_engines.kube.KubernetesExecutor
  RABBITMQ_ADMIN_USER: admin
  RABBITMQ_HOST: queue
  TUMBO_DOCKER_MEM_LIMIT: 128m
  TUMBO_DOCKER_IMAGE: 'philipsahli/tumbo-worker:v0.5.0-dev'
  ALLOWED_HOSTS: '*'
  FRONTEND_HOST: '{{ HOST }}'
  NEWRELIC_LICENSE: '{{ NEWRELIC_LICENSE }}'
  TUMBO_SOCIAL_AUTH: "True"
  SOCIAL_AUTH_GITHUB_KEY: "{{ SOCIAL_AUTH_GITHUB_KEY }}"
  SOCIAL_AUTH_GITHUB_SECRET: "{{ SOCIAL_AUTH_GITHUB_SECRET }}"
  SOCIAL_AUTH_USER_GROUP: "{{ SOCIAL_AUTH_USER_GROUP }}"
  DIGITALOCEAN_ZONE: "{{ DIGITALOCEAN_ZONE }}"
  DIGITALOCEAN_CONFIG: "{{ DIGITALOCEAN_CONFIG }}"

  